// scenario
#define BUDGET 800000000
#define STARTING_YEAR 1
#define STARTING_MONTH 1
#define LAST_YEAR 10
#define LAST_MONTH 12
#define TIGER_START 0
#define EAGLE_START 0
#define CHICKEN_START 0
#define TIGER_CAGE_START 0
#define EAGLE_CAGE_START 0
#define CHIKCEN_CAGE_START 0
// cage values
#define TIGER_CAGE_BUY_PRICE 2000
#define TIGER_CAGE_SELL_PRICE 500
#define EAGLE_CAGE_BUY_PRICE 2000
#define EAGLE_CAGE_SELL_PRICE 500
#define CHICKEN_CAGE_BUY_PRICE 300
#define CHICKEN_CAGE_SELL_PRICE 50
#define TIGER_CAGE_CAPACITY 3
#define EAGLE_CAGE_CAPACITY 4
#define CHICKEN_CAGE_CAPACITY 10
// visitor per month
#define HIGH_SEASON_START 5 
#define LOW_SEASON_START 10
#define TIGER_HIGH_VISITOR 30
#define TIGER_LOW_VISITOR 5
#define EAGLE_HIGH_VISITOR 15
#define EAGLE_LOW_VISITOR 7
#define CHICKEN_HIGH_VISITOR 2
#define CHICKEN_LOW_VISITOR 0.5
// ticket price
#define TICKET_PRICE 30
// event probability
#define FIRE_RATE 1
#define STEAL_RATE 1
#define PEST_RATE 20
#define ROTTEN_MEAT_RATE 10
//  death and sickness probality
#define SICKNESS_MORTALITY 10
#define TIGER_CHILD_MORTALITY 33
#define EAGLE_CHILD_MORTALITY 50
#define CHICKEN_CHILD_MORTALITY 50
#define SURPOPULATION_DEATH 50
#define TIGER_SICKNESS_PROBA 30
#define EAGLE_SICKNESS_PROBA 10
#define CHICKEN_SICKNESS_PROBA 5
#define TIGER_OVERCROWD_SICKNESS 20
#define EAGLE_OVERCROWD_SICKNESS 10
#define CHICKEN_OVERCROWD_SICKNESS 5
#define HEALING_PROBA 50
// sickness duration (in days, not sure to keep it)
#define TIGER_SICKNESS_DURATION 15
#define EAGLE_SICKNESS_DURATION 30
#define CHICKEN_SICKNESS_DURATION 5
// age of death (in month)
#define TIGER_LIFESPAWN 300
#define EAGLE_LIFESPAWN 300
#define CHICKEN_LIFESPAWN 180
// death when overcrowded
#define TIGER_SURPOP_LOSS 1
#define EAGLE_SURPOP_LOSS 1
#define CHICKEN_SURPOP_LOSS 4
// animal price
#define YOUNG_TIGER_BUY_PRICE 3000
#define YOUNG_TIGER_SELL_PRICE 1500
#define ADULT_TIGER_BUY_PRICE 120000
#define ADULT_TIGER_SELL_PRICE 60000
#define OLD_TIGER_BUY_PRICE 60000
#define OLD_TIGER_SELL_PRICE 10000
#define YOUNG_EAGLE_BUY_PRICE 1000
#define YOUNG_EAGLE_SELL_PRICE 500
#define ADULT_EAGLE_BUY_PRICE 4000
#define ADULT_EAGLE_SELL_PRICE 2000
#define OLD_EAGLE_BUY_PRICE 2000
#define OLD_EAGLE_SELL_PRICE 400
#define YOUNG_HEN_BUY_PRICE 20
#define YOUNG_HEN_SELL_PRICE 10
#define YOUNG_ROOSTER_BUY_PRICE 100
#define YOUNG_ROOSTER_SELL_PRICE 20
// sexual maturity
#define MALE_TIGER_MATURITY 6
#define FEMALE_TIGER_MATURITY 4
#define MALE_EAGLE_MATURITY 4
#define FEMALE_EAGLE_MATURITY 4
#define HEN_MATURITY 1
#define ROOSTER_MATURITY 2
// old_peepee_age
#define MALE_TIGER_UNFERTILITY_AGE 12
#define FEMALE_TIGER_UNFERTILITY_AGE 12
#define MALE_EAGLE_UNFERTILITY_AGE 12
#define FEMALE_EAGLE_UNFERTILITY_AGE 12
#define HEN_UNFERTILITY_AGE 8
#define ROOSTER_UNFERTILITY_AGE 8
// gestation time (month)
#define TIGER_GESTATION 3
#define EAGLE_GESTATION_ 2
#define CHICKEN_GESTATION 1
// gestaiton cd (month)
#define TIGER_GESTATION_CD 20
// food price
#define MEAT_PRICE 5
#define SEED_PRICE 2.5
// food per animal
#define MALE_TIGER_MEAL 180
#define FEMALE_TIGER_MEAL 150
#define MALE_EAGLE_MEAL 0.75
#define FEMALE_EAGLE_MEAL 1
#define HEN_MEAL 4.5
#define ROOSTER_MEAL 2.7
// month before hunger
#define MALE_TIGER_HUNGDAY 2
#define FEMALE_TIGER_HUNGDAY 2
#define MALE_EAGLE_HUNGDAY 10
#define FEMALE_EAGLE_HUNGDAY 10
#define HEN_HUNGDAY 1
#define ROOSTER_HUNGDAY 2
// food loss multiplicator
#define MEAT_LOSS 0.2
#define SEED_LOSS 0.1
// subvention 
#define TIGER_BONUS = 43800
#define EAGLE_BONUS = 2190
