// scenario
#define BUDGET 80000
#define STARTING_YEAR 1
#define STARTING_MONTH 1
#define LAST_YEAR 10
#define LAST_MONTH 12
#define TIGER_START 0
#define EAGLE_START 0
#define CHICKEN_START 0
#define TIGER_CAGE_START 0
#define EAGLE_CAGE_START 0
#define CHIKCEN_CAGE_START 0
// cage values
#define TIGER_CAGE_BUY_PRICE 2000
#define TIGER_CAGE_SELL_PRICE 500
#define EAGLE_CAGE_BUY_PRICE 2000
#define EAGLE_CAGE_SELL_PRICE 500
#define CHICKEN_CAGE_BUY_PRICE 300
#define CHICKEN_CAGE_SELL_PRICE 50
#define TIGER_CAGE_CAPACITY 2
#define EAGLE_CAGE_CAPACITY 4
#define CHICKEN_CAGE_CAPACITY 10
// visitor per month
#define TIGER_HIGH_VISITOR 30
#define TIGER_LOW_VISITOR 5
#define EAGLE_HIGH_VISITOR 15
#define EAGLE_LOW_VISITOR 7
#define CHICKEN_HIGH_VISITOR 2
#define CHICKEN_LOW_VISITOR 0.5
// ticket price
#define FAMILY_PRICE 30
// event probability
#define FIRE_RATE 1
#define STEAL_RATE 1
#define PEST_RATE 20
#define ROTTEN_MEAT_RATE 10
//  death and sickness probality
#define SICKNESS_MORTALITY 10
#define TIGER_CHILD_MORTALITY 33
#define EAGLE_CHILD_MORTALITY 50
#define CHICKEN_CHILD_MORTALITY 50
#define SURPOPULATION_DEATH 50
#define TIGER_SICKNESS 20
#define EAGLE_SICKNESS 10
#define CHICKEN_SICKNESS 5
// sickness duration
#define TIGER_SICKNESS_DURATION 15
#define EAGLE_SICKNESS_DURATION 30
#define CHICKEN_SICKNESS_DURATION 5
// age of death (in years)
#define MALE_TIGER_LIFESPAWN 25
#define FEMALE_TIGER_LIFESPAWN 25
#define MALE_EAGLE_LIFESPAWN 25
#define FEMALE_EAGLE_LIFESPAWN 25
#define HEN_LIFESPAWN 15
#define ROOSTER_LIFESPAWN 15
// death when overcrowded
#define CHICKEN_SURPOP_LOSS 1
#define EAGLE_SURPOP_LOSS 1
#define TIGER_SURPOP_LOSS 4
// animal price
#define YOUNG_TIGER_BUY_PRICE 3000
#define YOUNG_TIGER_SELL_PRICE 1500
#define ADULT_TIGER_BUY_PRICE 120000
#define ADULT_TIGER_SELL_PRICE 60000
#define OLD_TIGER_BUY_PRICE 60000
#define OLD_TIGER_SELL_PRICE 10000
#define YOUNG_EAGLE_BUY_PRICE 1000
#define YOUNG_EAGLE_SELL_PRICE 500
#define ADULT_EAGLE_BUY_PRICE 4000
#define ADULT_EAGLE_SELL_PRICE 2000
#define OLD_EAGLE_BUY_PRICE 2000
#define OLD_EAGLE_SELL_PRICE 400
#define YOUNG_HEN_BUY_PRICE 20
#define YOUNG_HEN_SELL_PRICE 10
#define YOUNG_ROOSTER_BUY_PRICE 100
#define YOUNG_ROOSTER_SELL_PRICE 20
// sexual maturity
#define MALE_TIGER_MATURITY 6
#define FEMALE_TIGER_MATURITY 4
#define MALE_EAGLE_MATURITY 4
#define FEMALE_EAGLE_MATURITY 4
#define HEN_MATURITY 1
#define ROOSTER_MATURITY 2
// old_peepee_age
#define MALE_TIGER_UNFERTILITY_AGE 12
#define FEMALE_TIGER_UNFERTILITY_AGE 12
#define MALE_EAGLE_UNFERTILITY_AGE 12
#define FEMALE_EAGLE_UNFERTILITY_AGE 12
#define HEN_UNFERTILITY_AGE 8
#define ROOSTER_UNFERTILITY_AGE 8
// gestation time (month)
#define TIGER_GESTATION 3
#define EAGLE_GESTATION_ 1.5
#define CHICKEN_GESTATION 0.66
// food price
#define MEAT_PRICE 5
#define SEED_PRICE 2.5
// food per animal
#define MALE_TIGER_MEAL 12
#define FEMALE_TIGER_MEAL 10
#define MALE_EAGLE_MEAL 0.25
#define FEMALE_EAGLE_MEAL 0.3
#define HEN_MEAL 0.15
#define ROOSTER_MEAL 0.18
// month before hunger
#define MALE_TIGER_HUNGDAY 2
#define FEMALE_TIGER_HUNGDAY 2
#define MALE_EAGLE_HUNGDAY 10
#define FEMALE_EAGLE_HUNGDAY 10
#define HEN_HUNGDAY 1
#define ROOSTER_HUNGDAY 2
// subvention 
#define TIGER_BONUS = 43800
#define EAGLE_BONUS = 2190
